# Generated by Django 3.2 on 2026-04-17 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_1', models.CharField(default='random', max_length=10)),
                ('color_2', models.CharField(default='random', max_length=10)),
                ('color_3', models.CharField(default='random', max_length=10)),
                ('ready_1', models.IntegerField(default=0)),
                ('ready_2', models.IntegerField(default=0)),
                ('ready_3', models.IntegerField(default=0)),
                ('disconnected_1', models.CharField(default='connected', max_length=20)),
                ('disconnected_2', models.CharField(default='connected', max_length=20)),
                ('disconnected_3', models.CharField(default='connected', max_length=20)),
                ('board', models.TextField()),
                ('status', models.CharField(default='', max_length=50)),
                ('player_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_1', to=settings.AUTH_USER_MODEL)),
                ('player_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_2', to=settings.AUTH_USER_MODEL)),
                ('player_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
