# Generated by Django 3.2.25 on 2026-04-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_sandbox',
            field=models.BooleanField(default=False),
        ),
    ]
